dataset:
  name: mnistc
  source_dataset: svhn
  clean_dataset: mnist
  clean_data_dir: datasets
  clean_download: true
  data_dir: datasets/mnist_c
  batch_size: 128
  num_workers: 2
  evaluation_mode: mixed
  mixed_seed: 0
  mixed_max_examples: 30000
  mixed_include_clean: true
  corruptions:
    - shot_noise
    - impulse_noise
    - glass_blur
    - motion_blur
    - shear
    - scale
    - rotate
    - brightness
    - translate
    - stripe
    - fog
    - spatter
    - dotted_line
    - zigzag
    - canny_edges
  severity_levels:
    - 1
